version: '3.9'
services:
  python:
    build:
      context: ./py-app  # the folder content
      dockerfile: Dockerfile.py-app
    environment:
      - "PORT=8081"
    expose:
      - "8081"

  javascript:
    build:
      context: ./express-app
      dockerfile: Dockerfile.express-app
    environment:
      - "PORT=8082"
    expose:
      - "8082"

  php:
    build:
      context: ./php-app
      dockerfile: Dockerfile.php-app
    environment:
      - "PORT=8083"
    expose:
      - "8083"

  go:
    build:
      context: ./go-app
      dockerfile: Dockerfile.go-app
    environment:
      - "PORT=8084"
    expose:
      - "8084"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:  # run after those 2 services
      - python
      - javascript
      - php
      - go