version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - ".env.db"
    expose:
      - "5432"
    restart: always
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

  redis:
    image: redis
    expose:
      - "6379"
    restart: always
    volumes:
      - "redis_data:/data"
    entrypoint: "redis-server --appendonly yes"

  django:
    build:
      context: ./django-app
      dockerfile: Dockerfile.django-app
    environment:
      - "PORT:8085"
    expose:
      - "8085"
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - './staticfiles:/app/staticfiles/'

  python:
    build:
      context: ./py-app  # the folder content
      dockerfile: Dockerfile.py-app  # dockerfile running from that folder
    environment:  # environment variables
      - "PORT=8081"
    expose:  # This tells Docker which ports to open on the container's network interface
      - "8081"
    volumes:  # persistent data across all containers
      - "./persistent_data:/app/persistent_data"

  javascript:
    build:
      context: ./express-app
      dockerfile: Dockerfile.express-app
    environment:
      - "PORT=8082"
    expose:
      - "8082"
    volumes:
      - "./persistent_data:/app/persistent_data"

  php:
    build:
      context: ./php-app
      dockerfile: Dockerfile.php-app
    environment:
      - "PORT=8083"
    expose:
      - "8083"
    volumes:
      - "./persistent_data:/app/persistent_data"

  go:
    build:
      context: ./go-app
      dockerfile: Dockerfile.go-app
    environment:
      - "PORT=8084"
    expose:
      - "8084"
    volumes:
      - "./persistent_data:/app/persistent_data"

  nginx:
    build:
      context: ./nginx  # the folder content
      dockerfile: Dockerfile.nginx  # dockerfile running from that folder
    ports:
      - "8080:80"
    depends_on:  # run after those 4 services
      - django
      - python
      - javascript
      - php
      - go
    volumes:
      - "./staticfiles:/www/static/"

volumes:
  redis_data:
  postgres_data:
  persistent_data:
    external: false  # external true means that the volume was already created and just use it, to let docker compose create the volume just use external false
  staticfiles:
    external: false
